[workspace]

resolver = "2"
members = [
    "utils",
    "day01",
    "day02",
    "day04",
    "day05",
    "day06",
    "day08",
    "day09",
    "day11",
    "day12",
    "day13",
    "day14",
    "day15",
]